CREATE DATABASE IF NOT EXISTS $DATABASE_NAME;
CREATE USER IF NOT EXISTS "${USERDB_NAME}"@"%" IDENTIFIED BY "${USERDB_PASSW}"; 
ALTER USER "${USERDB_NAME}"@"%" IDENTIFIED BY "${USERDB_PASSW}";
GRANT ALL ON $DATABASE_NAME.* TO "${USERDB_NAME}"@"%" IDENTIFIED BY "${USERDB_PASSW}";
ALTER USER 'root'@'localhost' IDENTIFIED BY "${MARIADB_ROOT_PASSW}";
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY "${MARIADB_ROOT_PASSW}";
FLUSH PRIVILEGES;